name: Test 🧪 and deploy 🚀 on staging
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]

    name: Test on Node v${{ matrix.node }}
    steps:
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          #cache: 'pnpm'
          #cache-dependency-path: '**/pnpm-lock.yaml'
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Git Sumbodule Update
        run: |
          git submodule update --init
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Write the cypress.env.json file 📝
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
      - name: Write local env file
        run: cp .env.example .env.local
      - name: Cypress E2E tests 🧪
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm run build && pnpm run start 
          wait-on: "http://localhost:3000"
          wait-on-timeout: 130
          record: false
          tag: node-${{ matrix.node }}
          browser: chrome
          config: pageLoadTimeout=60000,baseUrl=http://localhost:3000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
      - name: Cypress Component tests 🧪
        uses: cypress-io/github-action@v4
        with:
          install: false
          start: pnpm run build && pnpm run start 
          command: pnpm run test:component
          wait-on: "http://localhost:3000"
          wait-on-timeout: 130
          record: false
          tag: node-${{ matrix.node }}
          browser: chrome
          config: pageLoadTimeout=60000,baseUrl=http://localhost:3000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY_COMPONENTS }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_PROJECT_ID: 7iq8xz

  deploy:
    name: 🚀 Deploy on staging server
    needs: tests
    if: github.ref == 'refs/heads/main'
    uses: dyne/workflows/.github/workflows/node-staging-deploy.yml@main
    secrets: inherit
    with:
      deploy_url: https://interfacer-gui-staging.dyne.org
